version: "2"

services:
  vcx-node:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: 164629628951.dkr.ecr.eu-central-1.amazonaws.com/vcx-node
    volumes:
      - "./config:/vcx-config"
      - "./src:/app/src"
      - "./indy-data:/root/.indy_client"
      - "./data:/data"
    command: nodemon src/server.js
    ports:
      - "5000:5000"
